export const STRINGS = {
    menu: 'menu',
    close: 'close',
    back: 'back',
    cakes: 'Cakes',
    shop: 'Shop',
    cart: 'Cart',
    orders: 'Orders',
    profile: 'Profile',
    about: 'About Us',
    ios: 'ios',
    android: 'android',
    privacyPolicy: 'Privacy Policy', 
    termsConditions: 'Terms & Conditions',
    register: 'Register', 
    msgOnline: 'You are online.',
    msgOffline: 'You are offline.',
    msgNoConnectivityTitle: 'No Connectivity',
    msgNoConnectivityContent: 'Please connect to the internet.',
    msgIncorrectCredentialsTitle: 'Error',
    msgIncorrectCredentialsContent: 'Incorrect credentials. Please try again!',
};